import {NextRequest} from "next/server";
import type {Analysis} from "@/lib/types";
const schema={type:"object",properties:{idea:{type:"string"},score:{type:"integer"},verdict:{type:"string"},summary:{type:"string"},scores:{type:"object",properties:{Market:{type:"integer"},Product:{type:"integer"},Business:{type:"integer"},Competition:{type:"integer"},Execution:{type:"integer"}},required:["Market","Product","Business","Competition","Execution"]},market:{type:"object",properties:{tam:{type:"string"},sam:{type:"string"},initial:{type:"string"},growth:{type:"string"},targetUsers:{type:"array",items:{type:"string"}},signals:{type:"array",items:{type:"string"}}},required:["tam","sam","initial","growth","targetUsers","signals"]},competition:{type:"array",items:{type:"object",properties:{name:{type:"string"},strength:{type:"string"},weakness:{type:"string"}},required:["name","strength","weakness"]}},product:{type:"object",properties:{mustHave:{type:"array",items:{type:"string"}},later:{type:"array",items:{type:"string"}},architecture:{type:"array",items:{type:"string"}}},required:["mustHave","later","architecture"]},business:{type:"object",properties:{arpu:{type:"string"},cac:{type:"string"},breakEven:{type:"string"},assumptions:{type:"array",items:{type:"string"}}},required:["arpu","cac","breakEven","assumptions"]},risks:{type:"array",items:{type:"object",properties:{title:{type:"string"},text:{type:"string"},severity:{type:"string"},test:{type:"string"}},required:["title","text","severity","test"]}},experiments:{type:"array",items:{type:"string"}},boardroom:{type:"array",items:{type:"object",properties:{role:{type:"string"},text:{type:"string"}},required:["role","text"]}}},required:["idea","score","verdict","summary","scores","market","competition","product","business","risks","experiments","boardroom"]};
const system=`You are VentureLens, a rigorous startup analyst. Analyze ONLY the user's startup idea. Never use canned examples. Infer the specific customer, problem, workflow, business model and technical/product requirements from the idea. Clearly distinguish hypotheses from facts. Do not invent precise market statistics as verified facts: use "unknown", "directional estimate", or ranges when evidence is unavailable. Identify likely competitors or substitute behaviors, but label them as likely/adjacent if not verified. Scores must reflect the specific idea. Return ONLY valid JSON matching the supplied schema.`;
export async function POST(req:NextRequest){const {idea}=await req.json(); if(!idea||typeof idea!=="string")return Response.json({error:"Idea is required"},{status:400});
const model=process.env.OLLAMA_MODEL||"llama3.2:3b";
const prompt=`Startup idea: ${idea}

Produce a complete VentureLens analysis for THIS idea. Be concrete and specific. For market values, do not pretend estimates are researched facts. Suggested validation experiments must directly test the highest-risk assumptions. JSON schema: ${JSON.stringify(schema)}`;
try{const controller=new AbortController(); const timeout=setTimeout(()=>controller.abort(),180000);
const r=await fetch("http://127.0.0.1:11434/api/chat",{signal:controller.signal,method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({model,messages:[{role:"system",content:system},{role:"user",content:prompt}],stream:false,format:schema,options:{temperature:0.1}})}); clearTimeout(timeout); if(!r.ok)throw new Error("Ollama unavailable"); const j=await r.json(); const data=JSON.parse(j.message.content) as Analysis; return Response.json(data)}catch(e){return Response.json({error:"LOCAL_AI_UNAVAILABLE",message:e instanceof Error && e.name==="AbortError" ? `The local model took too long. Try a smaller model such as ${model}.` : `VentureLens could not complete the local AI analysis. Make sure Ollama is running and the model ${model} is installed.`,model},{status:503})}}